name: Add Random Number to Issue
on:
  push:
    branches:
      - main 

jobs:
  add_random_number_to_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate random number
        id: random_number
        run: echo "::set-output name=random::$(shuf -i 1-1000 -n 1)"
      
      - name: Create Issue
        run: |
          echo "Creating issue..."
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues \
          -d '{"title": "Random Number: ${{ steps.random_number.outputs.random }}"}'
